MDScreen:
    name: "origen2"
    MDFloatLayout:
        md_bg_color: 1,1,1,1
        
        Image:
            source:"Renovarse1.png"
            pos_hint:{"center_x":.5,"center_y": .65}
            
        MDLabel:
            text: "D E L R O M A"
            font_size: "30sp"
            pos_hint: {"center_y": .38}
            halign: "center"
            color: rgba(34,34,34,255)
            
            
        MDLabel:
            text: "Usuario Creado"
            font_size: "18sp"
            size_hint_x: .85
            pos_hint: {"center_x": .5,"center_y": .3}
            halign: "center"
            color: rgba(127,127,127,255)
            
        Button:
            text: "Ingresar"
            size_hint: .66, .065
            pos_hint: {"center_x": .5, "center_y": .15}
            halign: "center"
            background_color:0,0,0,0
            on_release:
                root.manager.transition.direction ="left"
                root.manager.current = "login2"
            canvas.before:
                Color:
                    rgb: rgba(52, 0, 231,255)
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [5]

        