# Generated by Django 4.2.1 on 2023-05-23 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_pedido", models.CharField(max_length=100)),
                ("domicilio", models.CharField(max_length=100)),
                ("cantidad_mesa", models.CharField(max_length=100)),
                ("cantidad_sillones", models.CharField(max_length=100)),
                ("cantidad_puff", models.CharField(max_length=100)),
                ("comentarios", models.TextField()),
                ("total_pedido", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_producto", models.CharField(max_length=100)),
                ("nombre_producto", models.CharField(max_length=100)),
                ("descripcion_producto", models.TextField()),
                ("precio_producto", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(name="Project",),
        migrations.AddField(
            model_name="pedidos",
            name="nombre_producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.producto",
                verbose_name="id_producto",
            ),
        ),
        migrations.AddField(
            model_name="pedidos",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.user",
                verbose_name="email",
            ),
        ),
    ]
