# Generated by Django 4.2.1 on 2023-05-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_pedidos_producto_user_delete_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="pedidos", name="id_pedido",),
        migrations.RemoveField(model_name="producto", name="id_producto",),
        migrations.AlterField(
            model_name="pedidos",
            name="cantidad_mesa",
            field=models.IntegerField(verbose_name=100),
        ),
        migrations.AlterField(
            model_name="pedidos",
            name="cantidad_puff",
            field=models.IntegerField(verbose_name=100),
        ),
        migrations.AlterField(
            model_name="pedidos",
            name="cantidad_sillones",
            field=models.IntegerField(verbose_name=100),
        ),
        migrations.AlterField(
            model_name="pedidos",
            name="total_pedido",
            field=models.IntegerField(verbose_name=100),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_producto",
            field=models.IntegerField(verbose_name=100),
        ),
    ]
